language: python
sudo: false
env:
  global:
    - PYTHON_VERSION=2.7
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  # install a few of the dependencies that pip would otherwise try to install
  # when intalling scikit-bio
  - travis_retry conda create --yes -n fastunifrac python=2.7 qiime matplotlib=1.4.3 mock nose -c bioconda
  - source activate fastunifrac
  - conda install -y flake8
  - travis_retry pip install . --process-dependency-links
script:
  - nosetests --with-doctest --with-coverage -v --cover-package=fastunifrac
  - flake8 fastunifrac/* setup.py scripts/*
after_success:
  - coveralls
